// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainJourneyWebApis.Data;

#nullable disable

namespace TrainJourneyWebApis.Migrations
{
    [DbContext(typeof(TrainJourneyContext))]
    partial class TrainJourneyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainJourneyWebApis.Models.GeneratedStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JourneyStageId")
                        .HasColumnType("int");

                    b.Property<string>("StoryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JourneyStageId");

                    b.ToTable("GeneratedStories");
                });

            modelBuilder.Entity("TrainJourneyWebApis.Models.JourneyStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JourneyStages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = -25.747900000000001,
                            Longitude = 28.229299999999999,
                            Name = "Pretoria",
                            SequenceOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Latitude = -28.728200000000001,
                            Longitude = 24.7623,
                            Name = "Kimberley",
                            SequenceOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Latitude = -32.344499999999996,
                            Longitude = 22.582999999999998,
                            Name = "Beaufort West",
                            SequenceOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Latitude = -33.646500000000003,
                            Longitude = 19.445900000000002,
                            Name = "Worcester",
                            SequenceOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Latitude = -33.924900000000001,
                            Longitude = 18.424099999999999,
                            Name = "Cape Town",
                            SequenceOrder = 5
                        });
                });

            modelBuilder.Entity("TrainJourneyWebApis.Models.GeneratedStory", b =>
                {
                    b.HasOne("TrainJourneyWebApis.Models.JourneyStage", "JourneyStage")
                        .WithMany()
                        .HasForeignKey("JourneyStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JourneyStage");
                });
#pragma warning restore 612, 618
        }
    }
}
